### ISSUE TITLE
flutter - "No such file or directory"

### ISSUE THREAD

**Issue by vishna** [mmcc007/sylph#62] opened 2019-08-27 19:43 UTC
Obviously I have flutter in my path 🤷‍♀️ 

```
Starting Sylph run 'sylph run 2019-08-27 21:35:56.363' on AWS Device Farm ...
Config file: sylph.yaml
Unpacking sylph resources to /tmp/sylph
Creating test bundle for upload...
Unhandled exception:
ProcessException: No such file or directory
  Command: flutter packages get
#0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:489:7)
#1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:634:18)
#2      Process.runSync (dart:io-patch/process_patch.dart:66:12)
#3      cmd (package:sylph/src/utils.dart:39:26)
#4      bundleFlutterTests (package:sylph/src/bundle.dart:52:3)
<asynchronous suspension>
#5      sylphRun (package:sylph/src/sylph_run.dart:48:9)
<asynchronous suspension>
#6      main (file:///Users/vishna/.pub-cache/hosted/pub.dartlang.org/sylph-0.4.0/bin/main.dart:80:13)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by vishna** [comment] 2019-08-27 20:11
I've checked out the repo locally, added it to dev_dependencies and got a bit further:

```
dev_dependencies:
  sylph:
    path: ../sylph
```

```
flutter packages pub run sylph:main
```

yet it still compains about missing `flutter`

```
Starting Sylph run 'sylph run 2019-08-27 22:01:32.785' on AWS Device Farm ...
Config file: sylph.yaml
Unpacking sylph resources to /tmp/sylph
Creating test bundle for upload...
Test bundle created (size 961 MB)

Running 'example tests 1' test suite...

Running tests concurrently on Android pools...
Running test suite 'example tests 1'  in project 'test concurrent runs' on pool 'android pool 1'...
Creating new device pool 'android pool 1' ...
Building debug .apk from test_driver/app.dart...
Unhandled exception:
ProcessException: No such file or directory
  Command: flutter build apk -t test_driver/app.dart --debug
#0      streamCmd (package:sylph/src/utils.dart:54:19)
<asynchronous suspension>
#1      _buildUploadApp (package:sylph/src/sylph_run.dart:160:11)
<asynchronous suspension>
#2      runSylphJob (package:sylph/src/sylph_run.dart:118:24)
<asynchronous suspension>
#3      runSylphJobInIsolate (package:sylph/src/concurrent_jobs.dart:39:27)
<asynchronous suspension>
#4      IsolateRunnerRemote._handleCommand.<anonymous closure> (package:isolate/isolate_runner.dart:298:43)
#5      new Future.sync (dart:async/future.dart:224:31)
#6      IsolateRunnerRemote._handleCommand (package:isolate/isolate_runner.dart:298:17)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

ideas what could it be?

**Comment by mmcc007** [comment] 2019-08-28 03:35
Couldn't reproduce the problem in my setup using sylph v0.4.0. 

If I was to take a guess, it could be something to do with the setup of the shell you are running in.
It looks like the process, which is running the flutter command, is not inheriting the PATH env var correctly. 

You could try explicitly exporting path before running sylph:
```
export PATH
sylph
```

If still stuck maybe send output from:
```
echo $PATH
flutter doctor -v
pub global list
```
Also, if running on a non-us machine, apparently have to watch out for any non US-ASCII characters in your env vars. For details see:
https://api.dartlang.org/stable/2.4.1/dart-io/Process/start.html

Also, make sure the command works from the command line:
```
flutter build apk -t test_driver/app.dart --debug
```

**Comment by vishna** [comment] 2019-08-28 09:50
So I thought that:
- this happens because I export path to dart-sdk that's included in my flutter-sdk (I wanted to keep those in sync at all times)
- installing dart-sdk via homebrew and removing aforementioned would fix it... but no

It works on my CI (bitrise), doesn't work on my machine

...on CI I'm getting into
```
ERR : Could not find a file named "pubspec.yaml" in "/private/tmp/sylph/test_bundle".
```

☝️ This is probably due to me trying to instrument example app that is referencing lib that is level up in the directory, that lib isn't copied and thus the error on CI

```
\
|-lib
\-example (references lib)
```

**Comment by vishna** [comment] 2019-08-28 10:10
```
echo $PATH
/usr/local/bin:~/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/vishna/Library/Android/sdk/tools:/Users/vishna/Library/Android/sdk/platform-tools:~/flutter/bin:/Users/vishna/.pub-cache/bin

flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-DE)
    • Flutter version 1.7.8+hotfix.4 at /Users/vishna/flutter
    • Framework revision 20e59316b8 (6 weeks ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

pub global list
devtools 0.1.1
stagehand 3.2.0
sylph 0.4.0
```

**Comment by mmcc007** [comment] 2019-08-28 18:37
I'm using the version of dart shipped with flutter locally and in CI on travis.

Don't see what is causing problem with not finding flutter in sub-process with your setup. Maybe search for non-ascii chars in PATH using some pattern matcher technique. 

I recently added support for local packages. Until released, try it using:
```
pub global activate --source git https://github.com/mmcc007/screenshots.git
```

**Comment by mmcc007** [comment] 2019-08-28 19:38
Were you able to resolve the local packages issue on your CI?

**Comment by vishna** [comment] 2019-08-29 09:28
yes, I made a script to copy the outer directory as subdirectory. modify pubspec yaml and then it worked (on CI though). nice that you have sorted it already in sylph

**Comment by mmcc007** [comment] 2019-08-29 17:44
Since this is an issue that appears to be specific to your local setup and not apparently related to sylph, will probably be closing shortly. Feel free to provide more info, re-open or create new issue, etc...

**Closed as completed** 2019-08-30 08:18 UTC
Labels: good first issue
